import = [
    # "~/.config/alacritty/themes/themes/github_dark.toml"
    "~/.config/alacritty/themes/themes/alacritty_kanagawa.yml"
]

[font]
size = 13.0

[font.bold]
style = "Medium"

[font.bold_italic]
style = "Medium Italic"

[font.italic]
style = "Light Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Light"

[window]
opacity = 0.999
startup_mode = "Maximized"
